# Generated by Django 4.2.3 on 2023-08-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addressinfo",
            options={
                "ordering": ["pid"],
                "verbose_name": "省市县地址信息",
                "verbose_name_plural": "省市县地址信息",
            },
        ),
        migrations.AddField(
            model_name="addressinfo",
            name="note",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="说明"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="addressinfo",
            unique_together={("address", "note")},
        ),
        migrations.AlterModelTable(
            name="addressinfo",
            table="address",
        ),
    ]
