# Generated by Django 4.2.3 on 2023-08-18 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_student_teacher_teacherassistant"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.teacher",
                verbose_name="课程讲师",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.ManyToManyField(to="courses.course", verbose_name="课程"),
        ),
        migrations.AddField(
            model_name="teacherassistant",
            name="teacher",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.teacher",
                verbose_name="讲师",
            ),
        ),
    ]
