# Generated by Django 4.2.3 on 2023-08-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_teacher_teacherassistant_student_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addressinfo",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="addressinfo",
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name="addressinfo",
            table=None,
        ),
    ]
