# Generated by Django 4.2.3 on 2023-08-24 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_addressinfo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addressinfo",
            options={"verbose_name": "省市县地址信息", "verbose_name_plural": "省市县地址信息"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "get_latest_by": "created_at",
                "verbose_name": "课程信息表",
                "verbose_name_plural": "课程信息表",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["age"],
                "verbose_name": "学生信息",
                "verbose_name_plural": "学生信息",
            },
        ),
    ]
